# Generated by Django 5.2.7 on 2025-11-15 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_serviceprovider_serviceproviderreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('apartment_details', models.TextField()),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('provider_proposed_date', models.DateField(blank=True, null=True)),
                ('provider_proposed_time', models.TimeField(blank=True, null=True)),
                ('has_provider_responses', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provider_responses', 'Waiting Provider Responses'), ('confirmed', 'Confirmed by Resident'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed_by_provider', 'Completed by Provider'), ('completed_by_resident', 'Completed by Resident'), ('cancelled', 'Cancelled')], default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.servicecategory')),
                ('confirmed_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_requests', to='accounts.serviceprovider')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.serviceprovider')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='service_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('propose', 'Propose New Time')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('proposed_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_selected_by_resident', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.serviceprovider')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_responses', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('service_request', 'provider')},
            },
        ),
    ]
