# Generated by Django 5.2.7 on 2025-10-27 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.ImageField(upload_to='service_providers/photos/')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('govt_id_type', models.CharField(max_length=50)),
                ('govt_id_number', models.CharField(max_length=50)),
                ('govt_id_document', models.FileField(upload_to='service_providers/ids/')),
                ('address_proof', models.FileField(upload_to='service_providers/address_proofs/')),
                ('service_category', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('work_certificate', models.FileField(blank=True, null=True, upload_to='service_providers/certificates/')),
                ('working_hours', models.CharField(max_length=100)),
                ('service_area', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=200)),
                ('service_description', models.CharField(max_length=200)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='accounts.serviceprovider')),
            ],
        ),
    ]
